using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
using System.Threading.Tasks;

namespace Gerador_Mensagem_FpML
{
    public class TagsFpML
    {
        #region Tags

        public string VALOR_VARIAVEL_1 = "XXXXXX";
        public string VALOR_VARIAVEL_2 = "YYYYYY";
        public string N1N2N3 = "N1N2N3";
        public string HEADER = "<?xml version=\"1.0\"?>";
        public string tagRequestConfirmation = "<requestConfirmation xmlns:itau=\"http://www.itau.com.br/FpML-5/confirmation\" xmlns:ext=\"http://www.fpml.org/FpML-5/ext\" xmlns:xsi=\"http://www.w3.org/2001/XMLSchema-instance\" xmlns=\"http://www.fpml.org/FpML-5/confirmation\" xsi:schemaLocation=\"http://www.itau.com.br/FpML-5/confirmation ../../Schemas/fpml-itau-doc.xsd http://www.itau.com.br/FpML-5/confirmation ../../Schemas/fpml-itau-msg.xsd http://www.itau.com.br/FpML-5/confirmation ../../Schemas/fpml-itau-fixed-income.xsd http://www.itau.com.br/FpML-5/confirmation ../../Schemas/fpml-itau-repo.xsd http://www.fpml.org/FpML-5/confirmation ../../Schemas/confirmation/fpml-main-5-7.xsd\" fpmlVersion=\"5-7\">";
        public string tagHeader = "<header xsi:type=\"itau:RequestMessageHeader\">";
        public string tagMessageId = "<messageId messageIdScheme=\"\">XXXXXX</messageId>";
        public string tagSentBy = "<sentBy messageAddressScheme=\"\">XXXXXX</sentBy>";
        public string tagTimestamp = "<creationTimestamp>XXXXXX</creationTimestamp>";
        public string tagMonitoringKey = "<itau:monitoringKey>XXXXXX</itau:monitoringKey>";
        public string tagProductInformation = "<itau:productInformation><itau:productType>N1N2N3</itau:productType><itau:instrumentType /><itau:productId>N4</itau:productId></itau:productInformation></header>";
        public string tagIsCorrection = "<isCorrection>XXXXXX</isCorrection>";
        public string tagTrade = " <trade><tradeHeader xsi:type=\"itau:TradeHeader\"><partyTradeIdentifier xsi:type=\"itau:PartyTradeIdentifier\"><partyReference href=\"Parte\" /><versionedTradeId><tradeId tradeIdScheme=\"\">XXXXXX</tradeId>";
        public string tagVersion = "<version>1</version></versionedTradeId>";
        public string tagEKM = "<itau:ekmId>XXXXXX</itau:ekmId>";
        public string tagChaveNatural = "<linkId linkIdScheme=\"\" id=\"NaturalSystemKey\">XXXXXX</linkId>";
        public string tagChaveProcessoFuncional = "<linkId linkIdScheme=\"\" id=\"functionalCorporateKey\">XXXXXX</linkId>";
        public string tagStructureId = "<linkId linkIdScheme=\"\" id=\"StructuredTradeId\"></linkId>";
        public string tagItauTradeId = "<itau:internalTradeInformation><itau:tradeId tradeIdScheme=\"\">PENDENTE</itau:tradeId><itau:tradeId tradeIdScheme= \"\" id = \"ParentRelationShipId\">XXXXXX</itau:tradeId></itau:internalTradeInformation></partyTradeIdentifier>";
        public string tagEKMsInstrumentosCOE = "<itau:relatedEkmsInstruments>";
        public string tagEKMInstrumento = "<itau:ekmInstrumentId>XXXXXX</itau:ekmInstrumentId>";
        public string tagEKMsInstrumentosCOEEnd = "</itau:relatedEkmsInstruments>";
        public string tagPartyTradeInformation = "<partyTradeInformation xsi:type=\"itau:PartyTradeInformation\"><partyReference href=\"Parte\" /><unit>MesaCliente</unit><trader traderScheme=\"\">XXXXXX</trader>";
        public string tagTimestampSystem = "<timestamp><type timestampScheme=\"\">SenderSystemTimestamp</type><value>XXXXXX</value></timestamp>";
        public string tagFigura = "<itau:portfolio>XXXXXX</itau:portfolio>";
        public string tagPortfolio = "<itau:strategy>XXXXXX</itau:strategy>";
        public string tagTradeDate = "<itau:marketTrade>Onshore</itau:marketTrade></partyTradeInformation><tradeDate>XXXXXX</tradeDate></tradeHeader>";
        public string tagBondTransaction = "<itau:bondTransaction><buyerPartyReference href=\"Parte\" /><sellerPartyReference href=\"ContraParte\" />";
        public string tagValorOperacao = "<ext:notionalAmount><currency>XXXXXX</currency><amount>XXXXXX</amount></ext:notionalAmount>";
        public string tagPrice = "<ext:price><ext:cleanPrice>100</ext:cleanPrice><ext:cleanOfAccruedInterest>true</ext:cleanOfAccruedInterest></ext:price>";
        public string tagCoupon = "<couponType></couponType>";
        public string tagBond = "<ext:bond xsi:type=\"itau:Bond\"><instrumentId instrumentIdScheme=\"\">COE25</instrumentId><exchangeId>XXXXXX</exchangeId>";
        public string tagDataPrevistaVencimento = "<maturity>XXXXXX</maturity>";
        public string tagValorPrecoUnitario = "<parValue>XXXXXX</parValue>";
        public string tagBaseTaxa = "<dayCountFraction>XXXXXX</dayCountFraction>";
        public string tagFloatingRateParte = "<itau:floatingRateCalculation><floatingRateIndex>XXXXXX</floatingRateIndex>";
        public string tagPercentualIndexador = "<spreadSchedule><initialValue>XXXXXX</initialValue></spreadSchedule>";
        public string tagTaxaPre = "<initialRate>XXXXXX</initialRate>";
        public string tagReferenciaCotacao = "<itau:indexSource>XXXXXX</itau:indexSource>";
        public string tagCodigoAtributo = "<itau:indexAttribute>XXXXXX</itau:indexAttribute>";
        public string tagCodigoTipoAtributo = "<itau:indexAttributeType>XXXXXX</itau:indexAttributeType>";
        public string tagCodigoFamilia = "<itau:indexFamily>XXXXXX</itau:indexFamily>";
        public string tagCodigoTipoCotacaoLiquidacao = "<itau:timing>XXXXXX</itau:timing>";
        public string tagValorCotacaoInicial = "<itau:fixingIndex><itau:spotValue>XXXXXX</itau:spotValue><itau:type></itau:type>";
        public string tagDataFixingContratacao = "<itau:fixingIndexContract><itau:fixingDate>XXXXXX</itau:fixingDate>";
        public string tagQuantidadeFixingContratacao = "<itau:floatingRateFixing>XXXXXX</itau:floatingRateFixing></itau:fixingIndexContract>";
        public string tagDataFixingVencimento = "<itau:fixingIndexMaturity><itau:fixingDate>XXXXXX</itau:fixingDate>";
        public string tagQuantidadeFixingVencimento = "<itau:floatingRateFixing>XXXXXX</itau:floatingRateFixing></itau:fixingIndexMaturity>";
        public string tagFixingIndexEnd = "</itau:fixingIndex>";
        public string tagTipoFormaLiquidacao = "<itau:settlementType>XXXXXX</itau:settlementType>";
        public string tagCodigoInstrumentoFinanceiro = "<itau:exchangeContractNumber>XXXXXX</itau:exchangeContractNumber>";
        public string tagFloatingRateCalculationEnd = "</itau:floatingRateCalculation>";
        public string tagBondEnd = "</ext:bond>";
        public string tagDataInicioValorizacao = "<itau:effectiveDate>XXXXXX</itau:effectiveDate>";
        public string tagDataCarencia = "<itau:repurchaseGraceDate>XXXXXX</itau:repurchaseGraceDate>";
        public string tagTipoCondicaoMercadoLiquidacao = "<itau:quotationCharacteristic><measureType>XXXXXX</measureType></itau:quotationCharacteristic>";
        public string tagQuantidadeAtivosNegociado = "<itau:numberOfUnits>XXXXXX</itau:numberOfUnits>";
        public string tagModalidadeProduto = "<itau:modality>XXXXXX</itau:modality>";
        public string tagCondicaoResgateFinanceiro = "<itau:terminatingCondition>XXXXXX</itau:terminatingCondition>";
        public string tagIdOferta = "<itau:offerInformation><itau:offerId>XXXXXX</itau:offerId>";
        public string tagIndicadorOfertaPublica = "<itau:isPublicOffer>XXXXXX</itau:isPublicOffer></itau:offerInformation>";
        public string tagPrecoReferencia = "<itau:referencePrice>Fixed</itau:referencePrice>";
        public string tagDiasUteis = "<itau:businessDays>XXXXXX</itau:businessDays>";
        public string tagPercentualCapitalGarantidoCetip = "<itau:contractReturnPercentage>XXXXXX</itau:contractReturnPercentage>";
        public string tagPercentualBaseAplicacaoCaixa = "<itau:percentageOfNotional>XXXXXX</itau:percentageOfNotional>";
        public string tagTipoProtecaoContraProventos = "<itau:warningProceedsNumber>XXXXXX</itau:warningProceedsNumber>";
        public string tagIndicadorVariacaoQuanto = "<itau:quanto><itau:isQuantoVariance>XXXXXX</itau:isQuantoVariance>";
        public string tagValorParidadeQuanto = "<itau:initialRate>XXXXXX</itau:initialRate></itau:quanto>";
        public string tagModalidadeLiquidacao = "<itau:terminatingModality>XXXXXX</itau:terminatingModality>";
        public string tagAtributosRegistroCamara = "<itau:cetipRegistryAttributes>";
        public string tagTipoDirecaoBarreira = "<triggerType>XXXXXX</triggerType>";
        public string tagAtributosRegistroCamaraEnd = "</itau:cetipRegistryAttributes>";
        public string tagNumeroClienteParte = "<party id=\"Parte\" xsi:type=\"itau:Party\"><partyId>XXXXXX</partyId>";
        public string tagGrupoEconomico = "<itau:corporateGroup>XXXXXX</itau:corporateGroup>";
        public string tagPartyEnd = "</party>";
        public string tagNumeroClienteContraparte = "<party id=\"ContraParte\" xsi:type=\"itau:Party\"><partyId>XXXXXX</partyId>";
        public string tagSegmentoCliente = "<itau:partySegment>XXXXXX</itau:partySegment>";
        public string tagSecaoConta = "<account id=\"XXXXXX\" xsi:type=\"itau:Party\">";
        public string tagAccountIdScheme = "<accountId accountIdScheme= \"\">agency:accountNumber:checkDigit</accountId>";
        public string tagSecaoContaBancariaNumAgencia = "<itau:agency>XXXXXX</itau:agency>";
        public string tagSecaoContaBancariaNumConta = "<itau:accountNumber>XXXXXX</itau:accountNumber>";
        public string tagSecaoContaBancariaNumDV = "<itau:checkDigit>XXXXXX</itau:checkDigit>";
        public string tagTipoConta = "<accountType>XXXXXX</accountType>";
        public string tagTipoParteConta = "<accountBeneficiary href=\"XXXXXX\" />";
        public string tagNumeroBanco = "<itau:referenceBank><referenceBankId>XXXXXX</referenceBankId></itau:referenceBank>";
        public string tagEmpresaConglomerado = "<itau:servicingPartyId>XXXXXX</itau:servicingPartyId>";
        public string tagNumeroContaCamara = "<accountId>XXXXXX</accountId>";
        public string tagSecaoContaEnd = "</account>";
        public string tagTradeEnd = "</trade>";
        public string tagItauBondTransactionEnd = "</itau:bondTransaction>";
        public string tagRequestConfirmationEnd = "</requestConfirmation>";
        public string tagDeclear = "<deClear xsi:type=\"itau:deClear\"><tradeIdentifier>";
        public string tagPartyReference = "<partyReference href=\"XXXXXX\" />";
        public string tagUnit = "<unit></unit>";
        public string tagVersionedTradeId = "<versionedTradeId><tradeId tradeIdScheme=\"\">XXXXXX</tradeId>";
        public string tagOriginatingTradeId = "<originatingTradeId>";
        public string tagOriginatingTradeIdEnd = "</originatingTradeId>";
        public string tagEKMRelacionada = "<itau:relatedEkmsInstruments><itau:ekmInstrumentId>XXXXXX</itau:ekmInstrumentId></itau:relatedEkmsInstruments>";
        public string tagTradeIdentifierEnd = "</tradeIdentifier>";
        public string tagDataEfetivaVencimento = "<effectiveDate>XXXXXX</effectiveDate>";
        public string tagReason = "<reason>XXXXXX</reason>";
        public string tagItauTradeInformation = "<itau:tradeInformation>";
        public string tagTrader = "<trader traderScheme=\"\">XXXXXX</trader>";
        public string tagTimestamps = "<timestamps>";
        public string tagTimestampCreation = "<timestamp><type>SenderCreationTimestamp</type><value>XXXXXX</value></timestamp>";
        public string tagTimestampsEnd = "</timestamps>";
        public string tagExecutionVenueType = "<executionVenueType></executionVenueType>";
        public string tagComments = "<itau:comments />";
        public string tagItauTradeInformationEnd = "</itau:tradeInformation>";
        public string tagDeclearEnd = "</deClear>";
        public string tagTermination = "<termination><tradeIdentifier>";
        public string tagAgreementDate = "<agreementDate>XXXXXX</agreementDate>";
        public string tagPayment = "<payment>";
        public string tagComprador = "<payerPartyReference href=\"XXXXXX\" />";
        public string tagVendedor = "<buyerPartyReference href=\"XXXXXX\" />";
        public string tagMoedaLiquidacao = "<paymentAmount id=\"Notional\"><currency>XXXXXX</currency>";
        public string tagValor = "<amount>XXXXXX</amount>";
        public string tagPaymentEnd = "</paymentAmount></payment>";
        public string tagSizeChange = "<sizeChange><notionalReference href=\"Notional\" /><changeInNotionalAmount ><currency></currency><amount></amount></changeInNotionalAmount><outstandingNotionalAmount><currency></currency><amount></amount></outstandingNotionalAmount></sizeChange>";
        public string tagTaxAmount = "<itau:taxAmount><itau:taxType>XXXXXX</itau:taxType><itau:amount>YYYYYY</itau:amount></itau:taxAmount>";
        public string tagItauSwap = "<itau:swap>";
        public string tagItauSwapLeg = "<swapStream id=\"LegXXXXXX\" xsi:type=\"itau:InterestRateStream\">";
        public string tagPayer = "<payerPartyReference href=\"XXXXXX\" />";
        public string tagReceiver = "<receiverPartyReference href=\"XXXXXX\" />";
        public string tagDataEfetivaLegSwap = "<calculationPeriodDates id=\"legXXXXXXCalculationPeriodDates\"><effectiveDate>";
        public string tagUnadjustedDate = "<unadjustedDate>XXXXXX</unadjustedDate><dateAdjustments><businessDayConvention>NotApplicable</businessDayConvention></dateAdjustments>";
        public string tagDataEfetivaLegSwapEnd = "</effectiveDate>";
        public string tagDataLiquidacao = "<terminationDate>";
        public string tagDataLiquidacaoEnd = "</terminationDate>";
        public string tagCalculationPeriodAdjustementEFrequency = "<calculationPeriodDatesAdjustments><businessDayConvention>NotApplicable</businessDayConvention></calculationPeriodDatesAdjustments><calculationPeriodFrequency><periodMultiplier>1</periodMultiplier><period>T</period><rollConvention>NONE</rollConvention></calculationPeriodFrequency>";
        public string tagCalculationPeriodDatesEnd = "</calculationPeriodDates>";
        public string tagCalculationPeriodDatesReference = "<paymentDates><calculationPeriodDatesReference href=\"legXXXXXXCalculationPeriodDates\" />";
        public string tagsConstantesENotionalStepSchedule = "<paymentFrequency><periodMultiplier>1</periodMultiplier><period>T</period></paymentFrequency><payRelativeTo>LastPricingDate</payRelativeTo><paymentDatesAdjustments><businessDayConvention>NotApplicable</businessDayConvention></paymentDatesAdjustments></paymentDates><calculationPeriodAmount><calculation><notionalSchedule><notionalStepSchedule><initialValue>XXXXXX</initialValue>";
        public string tagMoedaSwap = "<currency>XXXXXX</currency></notionalStepSchedule></notionalSchedule>";
        public string tagFloatingRateCalculationSwap = "<itau:floatingRateCalculation><floatingRateIndex>XXXXXX</floatingRateIndex>";
        public string tagSpreadSchedule = "<spreadSchedule><initialValue>XXXXXX</initialValue></spreadSchedule>";
        public string tagCapRateSchedule = "<capRateSchedule><initialValue>XXXXXX</initialValue></capRateSchedule>";
        public string tagFloorRateSchedule = "<floorRateSchedule><initialValue>XXXXXX</initialValue></floorRateSchedule>";
        public string tagFloatingRateIndex = "<itau:floatingRateFixing>XXXXXX</itau:floatingRateFixing>";
        public string tagCalculationEnd = "</calculation></calculationPeriodAmount>";
        public string tagCashflows = "<cashflows><cashflowsMatchParameters>False</cashflowsMatchParameters><paymentCalculationPeriod xsi:type=\"itau:PaymentCalculationPeriod\"><calculationPeriod><unadjustedStartDate></unadjustedStartDate><notionalAmount></notionalAmount><floatingRateDefinition/></calculationPeriod><itau:cashFlowType></itau:cashFlowType><itau:currency></itau:currency></paymentCalculationPeriod><paymentCalculationPeriod xsi:type=\"itau:PaymentCalculationPeriod\"><calculationPeriod><unadjustedStartDate></unadjustedStartDate><notionalAmount></notionalAmount><floatingRateDefinition/></calculationPeriod><itau:cashFlowType>PrincipalExchange</itau:cashFlowType><itau:currency></itau:currency></paymentCalculationPeriod></cashflows>";
        public string tagBarreira = "<itau:barrier>";
        public string tagBarreiraEnd = "</itau:barrier>";
        public string tagBarreiraAlta = "<barrierCap>";
        public string tagLevelPercentage = "<trigger><levelPercentage>XXXXXX</levelPercentage></trigger>";
        public string tagBarreiraAltaEnd = "</barrierCap>";
        public string tagBarreiraBaixa = "<barrierFloor>";
        public string tagBarreiraBaixaEnd = "</barrierFloor>";
        public string tagMomentoVerificacaoBarreira = "<triggerDates>";
        public string tagData = "<date>XXXXXX</date>";
        public string tagMomentoVerificacaoBarreiraEnd = "</triggerDates>";
        public string tagValorBarreira = "<trigger><level>XXXXXX</level></trigger>";
        public string tagRebate = "<featurePayment>";
        public string tagMoedaRebate = "<currency>XXXXXX</currency>";
        public string tagRebateData = "<featurePaymentDate><adjustableDate>";
        public string tagRebateDataFixing = "<unadjustedDate>XXXXXX</unadjustedDate><dateAdjustments><businessDayConvention>NotApplicable</businessDayConvention></dateAdjustments>";
        public string tagRebateDataEnd = "</adjustableDate></featurePaymentDate>";
        public string tagRebateEnd = "</featurePayment>";
        public string tagTipoVerificacaoBarreira = "<itau:triggerDateType>XXXXXX</itau:triggerDateType>";
        public string tagTipoDataPagamentoRebate = "<itau:RebateDateType>XXXXXX</itau:RebateDateType>";
        public string tagItauSwapLegEnd = "</swapStream>";
        public string tagDayCountFraction = "<dayCountFraction>XXXXXX</dayCountFraction>";
        public string tagPremio = "<additionalPayment><payerPartyReference href=\"Parte\" /><receiverPartyReference href=\"ContraParte\" /><paymentAmount><currency></currency><amount></amount></paymentAmount><paymentDate><adjustedDate></adjustedDate></paymentDate><paymentType></paymentType></additionalPayment>";
        public string tagSwapInitialPrice = "<itau:swapInitialPrice><currency></currency><amount></amount></itau:swapInitialPrice>";
        public string tagSwapATermo = "<itau:forwardIndexCalculation>";
        public string tagDataFixing = "<itau:fixingDate>XXXXXX</itau:fixingDate>";
        public string tagSwapATermoEnd = "</itau:forwardIndexCalculation>";
        public string tagItauSwapEnd = "</itau:swap>";
        public string tagTerminationEnd = "</termination>";

        #endregion
    }
}
